%%
clear; clc;
load('Data/KITTI_result');

%% Expected number of true loop closures (NLC)

figure('Units','inches',...
'Position',[0 0 12 10],...
'PaperPositionMode','auto');
hold on; 
plot(nlc_result.K_comms, nlc_result.vgreedy_vals / nlc_result.best_val, '-bo','markersize',12,'markerfacecolor','b','linewidth',2);
plot(nlc_result.K_comms, nlc_result.egreedy_vals / nlc_result.best_val, '-kd','markersize',12,'markerfacecolor','k','linewidth',2);
plot(nlc_result.K_comms, nlc_result.rand_vals / nlc_result.best_val, '-ks','markersize',12,'markerfacecolor','k','linewidth',2);
plot(nlc_result.K_comms, nlc_result.cvx_vals / nlc_result.best_val, '--k*','markersize',12,'markerfacecolor','k','linewidth',2);


ylim([0 1])
xlim([0 150])
legend('Proposed Alg.', 'Edge Greedy', 'Random', 'Upper bound on OPT', 'Location', 'northwest');
title('Normalized NLC Score');
hold off;

set(gca, 'FontSize', 25);
hXLabel = xlabel('Communication Budget $b$', ...
    'FontSize', 25, ...
    'interpreter','latex');
hYLabel = ylabel('Normalized $$f_{\textrm{NLC}}$$', ...
    'FontSize', 25,'interpreter','latex');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 25          );
set(gca, ...
    'Box'         , 'on'     , ...
    'TickDir'     , 'out'     , ...
    'XMinorTick'  , 'on'     , ...
    'YMinorTick'  , 'on'      , ...
    'YGrid'       , 'on'      , ...
    'XGrid'       , 'on'      , ...
    'GridAlpha'   , 0.20       , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1         );

print(gcf, '-depsc', '-r600', ['plots/KITTI_nlc_result']); 

%% tree-connectivity (WST)

figure('Units','inches',...
'Position',[0 0 12 10],...
'PaperPositionMode','auto');
hold on; 
% Plot normalized performance
plot(wst_result.K_comms, wst_result.vgreedy_vals / wst_result.best_val, '-mo','markersize',12,'markerfacecolor','m','linewidth',2);
plot(wst_result.K_comms, wst_result.egreedy_vals / wst_result.best_val, '-kd','markersize',12,'markerfacecolor','k','linewidth',2);
plot(wst_result.K_comms, wst_result.rand_vals / wst_result.best_val, '-ks','markersize',12,'markerfacecolor','k','linewidth',2);
plot(wst_result.K_comms, wst_result.cvx_vals / wst_result.best_val, '--k*','markersize',12,'markerfacecolor','k','linewidth',2);


ylim([0 1])
xlim([0 150])
legend('Proposed Alg.', 'Edge Greedy', 'Random', 'Upper bound on OPT', 'Location', 'northwest');
hold off;

set(gca, 'FontSize', 25);
hXLabel = xlabel('Communication Budget $b$', ...
    'FontSize', 35, ...
    'interpreter','latex');
hYLabel = ylabel('Normalized  $$f_{\textrm{WST}}$$', ...
    'FontSize', 35,'interpreter','latex');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 35          );
set(gca, ...
    'Box'         , 'on'     , ...
    'TickDir'     , 'out'     , ...
    'XMinorTick'  , 'on'     , ...
    'YMinorTick'  , 'on'      , ...
    'YGrid'       , 'on'      , ...
    'XGrid'       , 'on'      , ...
    'GridAlpha'   , 0.20       , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1         );
    
plotpath = 'Plots/';
print(gcf, '-depsc', '-r600', ['plots/KITTI_wst_result']); 

%% D-optimality Criterion (FIM)
figure('Units','inches',...
'Position',[0 0 12 10],...
'PaperPositionMode','auto');
hold on; 
plot(fim_result.K_comms, fim_result.vgreedy_vals / fim_result.best_val, '-ro','markersize',12,'markerfacecolor','r','linewidth',2);
plot(fim_result.K_comms, fim_result.egreedy_vals / fim_result.best_val, '-kd','markersize',12,'markerfacecolor','k','linewidth',2);
plot(fim_result.K_comms, fim_result.rand_vals / fim_result.best_val, '-ks','markersize',12,'markerfacecolor','k','linewidth',2);

ylim([0 1])
xlim([0 150])
legend('Proposed Alg.', 'Edge Greedy', 'Random' , 'Location', 'northwest');
hold off;

set(gca, 'FontSize', 25);
hXLabel = xlabel('Communication Budget $b$', ...
    'FontSize', 25, ...
    'interpreter','latex');
hYLabel = ylabel('Normalized $$f_{\textrm{FIM}}$$', ...
    'FontSize', 25,'interpreter','latex');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 25          );
set(gca, ...
    'Box'         , 'on'     , ...
    'TickDir'     , 'out'     , ...
    'XMinorTick'  , 'on'     , ...
    'YMinorTick'  , 'on'      , ...
    'YGrid'       , 'on'      , ...
    'XGrid'       , 'on'      , ...
    'GridAlpha'   , 0.20       , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1         );

plotpath = 'Plots/';
print(gcf, '-depsc', '-r600', ['plots/KITTI_fim_result']); 

