        legend('Monolog', 'Optimal');
        xlabel('candidate radius (m)','FontSize',20,'interpreter','latex');
        ylabel('communication cost (kB)','FontSize',20,'interpreter','latex');
        set(gca, ...
            'Box'         , 'on'     , ...
            'TickDir'     , 'out'     , ...
            'XMinorTick'  , 'on'     , ...
            'YMinorTick'  , 'on'      , ...
            'YGrid'       , 'on'      , ...
            'XGrid'       , 'on'      , ...
            'XColor'      , [.3 .3 .3], ...
            'YColor'      , [.3 .3 .3], ...
            'LineWidth'   , 1.3         );
        hLegend = legend('Location','NorthWest');
        set(hLegend, 'interpreter', 'latex', 'FontSize', 15);